export enum AuthActionsType {
    LOGIN_START = 'auth/LOGIN_START',
    LOGIN_START_SUCCEED = 'auth/LOGIN_START_SUCCEED',
    LOGIN_START_FAIL = 'auth/LOGIN_START_FAIL',
    SIGNUP_START = 'auth/SIGNUP_START',
    SIGNUP_START_SUCCEED = 'auth/SIGNUP_START_SUCCEED',
    SIGNUP_START_FAIL = 'auth/SIGNUP_START_FAIL',
    LOGOUT = 'auth/LOGOUT',
}
