export enum CollectionActionType {
    FETCH_COLLECTIONS_START = 'collection/FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCEED = 'collection/FETCH_COLLECTIONS_SUCCEED',
    FETCH_COLLECTIONS_FAILED = 'collection/FETCH_COLLECTIONS_FAILED',
    CLEAR_COLLECTION = 'collection/CLEAR_COLLECTION',
}
