export enum ProductActionType {
    FETCH_PRODUCTS_START = 'product/FETCH_PRODUCTS_START',
    FETCH_PRODUCTS_SUCCEED = 'product/FETCH_PRODUCTS_SUCCEED',
    FETCH_PRODUCTS_FAILED = 'product/FETCH_PRODUCTS_FAILED',
    CLEAR_PRODUCTS = 'product/CLEAR_PRODUCTS',
}
