export enum UserActionType {
    FETCH_USER_START = 'user/FETCH_USER_START',
    FETCH_USER_SUCCEED = 'user/FETCH_USER_SUCCEED',
    FETCH_USER_FAILED = 'user/FETCH_USER_FAILED',
    UPDATE_USER_START = 'user/UPDATE_USER_START',
    UPDATE_USER_SUCCEED = 'user/UPDATE_USER_SUCCEED',
    UPDATE_USER_FAILED = 'user/UPDATE_USER_FAILED',
    CLEAR_USER = 'user/CLEAR_USER',
}
