export enum WishListActionType {
    FETCH_WISHLIST_START = 'wish-list/FETCH_WISHLIST_START',
    FETCH_WISHLIST_SUCCEED = 'wish-list/FETCH_WISHLIST_SUCCEED',
    FETCH_WISHLIST_FAILED = 'wish-list/FETCH_WISHLIST_FAILED',
    TOGGLE_WISHLIST_START = 'wish-list/TOGGLE_WISHLIST_START',
    TOGGLE_WISHLIST_SUCCEED = 'wish-list/TOGGLE_WISHLIST_SUCCEED',
    TOGGLE_WISHLIST_FAILED = 'wish-list/TOGGLE_WISHLIST_FAILED',
    CLEAR_WISHLIST = 'wish-list/CLEAR_WISHLIST',
}
